"""empty message

Revision ID: 55f503ea281f
Revises: 5ca20200d3a2
Create Date: 2019-06-16 11:02:08.560828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f503ea281f'
down_revision = '5ca20200d3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('car_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'car_id')
    # ### end Alembic commands ###
