# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DigitalPower' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'Swinject'
  pod 'SwinjectStoryboard', '~> 2.2.0' 
  pod 'RealmSwift', '~> 3.7'
  # Pods for DigitalPower

end
